name: Build Builder Docker image

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "builder/**"
      - ".github/workflows/build-builder.yml"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
      with:
        fetch-depth: 0

    - name: Login to GitHub Container Registry
      run: |
        echo $GITHUB_TOKEN | docker login ghcr.io -u EmuDeck --password-stdin
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Build
      run: |
        cd builder
        docker build -t ghcr.io/deckbuild/builder:latest .

    - name: Wait for other runs to complete
      uses: softprops/turnstyle@8db075d65b19bf94e6e8687b504db69938dc3c65
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Push
      run: |
        docker push ghcr.io/EmuDeck/builder:latest

    - name: Log out of GitHub Container Registry
      run: |
        docker logout ghcr.io
